#########################################################################################################################################
# -= Requirements =-
#
# 1. Make sure ansible user has been created
# 1a. security login create -vserver CLUSTER96 -role admin -application http -authentication-method password -user-or-group-name ansible
# 1b. security login create -vserver CLUSTER96 -role admin -application ontapi -authentication-method password -user-or-group-name ansible
##########################################################################################################################################
---
- hosts: localhost
  gather_facts: false
  name: NetApp Network Setup
  vars:
    login: &login
     hostname: "{{ clusterip }}"
     username: "{{ user }}"
     password: "{{ pass }}"
     https: "{{ https_option }}"
     validate_certs: "{{ validate_certs_option }}"
  vars_files:
  - variables.yml
  tasks:
  - name: Setup VLAN
    na_ontap_net_vlan:
      state: present
      vlanid: "{{ vlan }}"
      node: "{{ item }}"
      parent_interface: "{{ parentinterface }}"
      <<: *login
    loop: # Add nodes below
     - "{{ clustername }}-01"
     - "{{ clustername }}-02"
  - name: Create Broadcast Domain
    na_ontap_broadcast_domain:
      state: present
      name: "{{ broadcastname }}"
      mtu: "1500"
      ipspace: Default
      ports: "{{ broadcastports }}"
      <<: *login
  - name: Create LIF
    na_ontap_interface:
      state: present 
      interface_name: "{{ lifinterfacename }}"
      home_port: "{{ lifhomeport }}"
      home_node: "{{ lifhomenode }}"
      role: data
      protocols: "{{ lifprotocols }}"
      admin_status: up
      failover_policy: system-defined
      firewall_policy: data
      is_auto_revert: true
      address: "{{ lifaddress }}" 
      netmask: "{{ lifnetmask }}"
      dns_domain_name: "{{ svmdnsdomain }}"
      vserver: "{{ vservername }}"
      <<: *login
  - debug: msg="VLAN {{ vlan }}, broadcast domain {{ broadcastname }}, subnet {{ subnetname}} and NFS lif {{ lifinterfacename }} have been setup."
